-- Reference: gsa.subscription_dashboard_type
-- Dashboard subscriptions page reads rows with is_visible = true.
-- Active subscription embeds use types where is_active = true (RLS allows both).
-- Apply grants/RLS from docs/supabase-gsa-schema-access.sql.

CREATE TABLE IF NOT EXISTS gsa.subscription_dashboard_type (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  description_esp text NULL,
  description_eng text NULL,
  days_valid integer NOT NULL DEFAULT 0,
  monthly_api_credits integer NOT NULL DEFAULT 0,
  price numeric(12, 2) NOT NULL DEFAULT 0,
  discount_percentage numeric(5, 2) NOT NULL DEFAULT 0,
  is_available boolean NOT NULL DEFAULT false,
  is_visible boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT subscription_dashboard_type_pkey PRIMARY KEY (id)
);

-- Example seed (adjust IDs/names to match production)
-- INSERT INTO gsa.subscription_dashboard_type
--   (name, description_esp, description_eng, days_valid, monthly_api_credits, price, discount_percentage, is_available, is_visible, is_active)
-- VALUES
--   ('Free', 'Prueba gratuita', 'Free trial', 5, 20, 0, 0, false, true, true),
--   ('Dashboard Solo', 'Acceso ilimitado al Dashboard', 'Unlimited Dashboard access', 30, 0, 9, 0, true, true, true),
--   ('Dashboard + Credits', 'Dashboard + créditos API', 'Dashboard + API credits', 30, 130, 15, 12, false, true, true);
