-- Roadmap tables (web_page.features + web_page.feature_types)
-- Used by /api/web-page/roadmap and home RoadmapSection.

CREATE TABLE IF NOT EXISTS web_page.feature_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name_eng text NOT NULL,
  name_esp text NULL,
  CONSTRAINT feature_types_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS web_page.features (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  feature_type_id bigint NOT NULL,
  feature_descripction_esp text NOT NULL,
  feature_description_eng text NOT NULL,
  feature_expected_desploy text NOT NULL,
  is_active boolean NOT NULL,
  is_completed boolean NULL,
  completed_at timestamp with time zone NULL,
  "order" integer NOT NULL,
  CONSTRAINT features_pkey PRIMARY KEY (id),
  CONSTRAINT features_feature_type_id_fkey FOREIGN KEY (feature_type_id)
    REFERENCES web_page.feature_types (id)
);

-- Permissions: run docs/supabase-web-page-grants.sql (includes service_role grants).
